on: push
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.x
      - run: dotnet test
